cloudforet-io/cost-analysis

src/spaceone/cost_analysis/model/cost_model.py

- Optimize Indexes for performance
- cost
- monthly_cost
- cost_query_history

refactor: optimize indexes of cost models

---

src/spaceone/cost_analysis/service/job_service.py

- Monthly Cost aggregation query fails when there is a lot of Cost data
- Monthly aggregation by region_code when cost data exceeds 100k

Refactor Cost Job Sync

---

src/spaceone/cost_analysis/service/job_service.py

- Add debug code when synchronizing data source

refactor: add debug code

---

src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/service/job_service.py

- Change key in monthly aggregate query on large cost data (`region_code` -> `product`)
- Optimize Index

Refactor Data Source Sync

---

src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/service/job_service.py

- Change `COMPOUND_INDEX_FOR_SYNC_JOB_1` index in cost model
- Add pagination for monthly data aggregation

Optimize data source sync

---

src/spaceone/cost_analysis/service/job_service.py

- Add allow_disk_use option when synchronizing data source

refactor: add allowDiskUse option when synchronizing data source

---

src/spaceone/cost_analysis/service/job_service.py

- change large_size condition when sync data source (100k -> 50k)

Refactor sync data source

---

src/spaceone/cost_analysis/model/data_source_model.py

- change updatable_fields in DataSource model
- https://github.com/cloudforet-io/cost-analysis/issues/25

Change DataSource model

---

src/spaceone/cost_analysis/info/data_source_info.py
src/spaceone/cost_analysis/service/cost_service.py

- add fields to data_source_info for performance
- cost_tags_keys
- cost_additional_info_keys
- apply cache for distinct queries in `Cost.stat` API

Refactor Cost Search

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/job_service.py

- Preload distinct values cache on data source sync
- Refactor logic to save cost `tags_keys` and `additional_info_keys`

Refactor Data Source 

---

src/spaceone/cost_analysis/manager/cost_manager.py

- change default `field_group` policy (default: null)

Change Field Group Policy

---

src/spaceone/cost_analysis/interface/grpc/v1/budget_usage.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/budget_usage_service.py
src/spaceone/cost_analysis/service/cost_service.py

- Add `BudgetUsage.analyze` API
- Refactor `Cost.analyze_v2` API

Implement Analyze API

---

src/spaceone/cost_analysis/manager/cost_manager.py

- Refactor date parsing code of `Cost.analyze_v2` API

Refactor Date Parsing Code

---

src/spaceone/cost_analysis/error/__init__.py
src/spaceone/cost_analysis/error/data_source_rule.py
src/spaceone/cost_analysis/info/data_source_rule_info.py
src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/model/data_source_rule_model.py
src/spaceone/cost_analysis/service/data_source_rule_service.py
test/factory/data_source_factory.py
test/factory/data_source_rule_factory.py
test/service/data_source_rule_service.py

Implement Custom Data Source Rule. 
The `data_source_type` of the data source rule updated by the plugin's metadata is defined as `MANAGED`.
The `data_source_type` of data source rules added by the user is defined as `CUSTOM` to separate from `MANAGED` .
The order priority is also managed separately between the two data source rules.
When cost data is inserted, if data source rule is existed, the cost data can be changed by the rule, and it is applied in the order of `MANAGED` and `CUSTOM`. (applied according to each priority)
* https://github.com/cloudforet-io/cost-analysis/issues/24

Implement Custom Data Source Rule

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py

- import `secret_data` from `global_conf.py`

Refactor DataSourcePluginConnector

---

src/spaceone/cost_analysis/service/job_service.py

- add analyze_v2 compatible code

Fix Data Source Sync Bug

---

src/spaceone/cost_analysis/service/job_service.py

chore: add debug code

---

src/spaceone/cost_analysis/service/job_service.py

fix: fix cache bug

---

src/spaceone/cost_analysis/error/data_source_rule.py
src/spaceone/cost_analysis/info/data_source_rule_info.py
src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/model/data_source_rule_model.py
src/spaceone/cost_analysis/service/data_source_rule_service.py
test/factory/data_source_rule_factory.py

Modify data_source_type to rule_type in DataSourceRule.
Modify data_source_type to rule_type in DataSourceRule.
This value defines the type for the data source rule, so it's exactly named rule_type .
* https://github.com/cloudforet-io/cost-analysis/issues/24

Modify data_source_type to rule_type in DataSourceRule

---

src/spaceone/cost_analysis/service/budget_usage_service.py
src/spaceone/cost_analysis/service/cost_service.py

- add keyword filter to `Cost.analyze_v2` API
- add keyword filter to `BudgetUsage.analyze` API

Add Option to Analyze API

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/job_service.py

- change to the budget usage update process
- add query log of budget usage

Fix Budget Usage Update Bug

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py

- Add `domain_id` filter to budget usage query for performance

refactor: add domain_id to budget usage query

---

src/spaceone/cost_analysis/manager/cost_manager.py

- fix wrong db query for performance

Fix DB Query

---

src/spaceone/cost_analysis/service/job_service.py

- fix budget usage bug
- change query when synchronizing costs

Fix bugs when synchronizing costs

---

src/spaceone/cost_analysis/info/cost_info.py

refactor: remove resource_group in cost

Remove resource_group in cost

---

src/spaceone/cost_analysis/manager/cost_manager.py

chore: remove an not used code

remove an not used code

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py

* As the transaction structure of the core framework changes, the transaction variable of the dependent microservice is removed.

Remove trasaction variable used when initializing in connector

---

src/spaceone/cost_analysis/manager/secret_manager.py

* add token argument in SpaceConnector of secret service

Add token argument in SpaceConnector of secret service

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py

* Delete metadata in data_source_plugin_connector

Delete metadata in data_source_plugin_connector

---

src/spaceone/cost_analysis/manager/job_task_manager.py

* Change metadata in push_job_task method

Change metadata in push_job_task method

---

deploy/helm/values.yaml
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py

* Change hourly scheduler to interval scheduler for debug

Change hourly scheduler to interval scheduler for debug

---

deploy/helm/values.yaml

Change scheduler settings in helm values

Change scheduler settings in helm values

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py

* Add minute args in DataSourceSyncScheduler

Add minute args in DataSourceSyncScheduler

---

src/spaceone/cost_analysis/manager/plugin_manager.py

* Add token args in SpaceConnector

Add token args in SpaceConnector

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py

* Change IntervalScheduler to HourlyScheduler in DataSourceSyncScheduler

Change IntervalScheduler to HourlyScheduler in DataSourceSyncScheduler

---

src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/plugin_manager.py
src/spaceone/cost_analysis/service/data_source_rule_service.py

|Worker|Resource|Verb|SpaceConnector|Manager|
|:---|---|:---|:---:|:---:|
|cost-analysis|Job|create_jobs_by_data_source|O|plugin, data_source_plugin, identity|

Change so that TOKEN can be obtained from GLOBAL when using SpaceConnector in worker

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/job_manager.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

- add feature remove cost data with data source
- this feature remove cost and monthly cost data with datasource after that update cache  
* #66

Add feature remove cost data with data source

---

src/spaceone/cost_analysis/info/data_source_info.py
src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

add secret_type and secret_filter

secret_type and secret_filter

---

src/spaceone/cost_analysis/model/data_source_model.py

fix: secret_type string length

Secret_type string length

---

src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

Move to method

---

src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/job_service.py

Add to_dict for secret_filter

---

src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/service/job_service.py

Add secret_type in options

---

src/spaceone/cost_analysis/manager/repository_manager.py
src/spaceone/cost_analysis/service/data_source_service.py

Add secret_filter validation method

Add secret_filter validation method

---

src/spaceone/cost_analysis/service/data_source_service.py

chore: add logger for debug

---

src/spaceone/cost_analysis/service/job_service.py

fix: secret_filter in data_source

secret_filter in data_source

---

src/spaceone/cost_analysis/service/job_service.py

Add secret_type for None

---

src/spaceone/cost_analysis/service/job_service.py

Add start option

---

src/spaceone/cost_analysis/error/job.py
src/spaceone/cost_analysis/service/job_service.py

- fix bug when sync data source of `USE_SERVICE_ACCOUNT_SECRET` type

fix: fix bug when sync data source of USE_SERVICE_ACCOUNT_SECRET type

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/cost_service.py

- change cache key of `CostQuerySet`
- change date format in analyze API

Refactor Cost Analysis

---

src/spaceone/cost_analysis/manager/cost_manager.py

refactor: refactor analyze query

---

src/spaceone/cost_analysis/service/job_service.py

fix: fix query bug

---

src/spaceone/cost_analysis/service/job_service.py

refactor: refacto job close logic

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/service/budget_usage_service.py
src/spaceone/cost_analysis/service/cost_service.py

- optimize cost query options
- optimize budget usage query options

Optimize Analyze Query

---

src/spaceone/cost_analysis/service/budget_service.py

- add default currency when creating a budget

fix: add default currency when creating a budget

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/service/budget_service.py

- de-duplicate budget target (`project_id` or `project_group_id`)

refactor: de-duplicate budget target (project_id or project_group_id)

---

src/spaceone/cost_analysis/manager/cost_manager.py

- fix wrong `project_group_id` data when syncing data source

fix: fix wrong project_group_id data when sync data source

---

src/spaceone/cost_analysis/service/cost_query_set_service.py

feat: change require field

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/manager/__init__.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/notification_manager.py
src/spaceone/cost_analysis/model/budget_model.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/job_service.py

- implement budget alarm
- clean old cost data

Implement Budget Alarm 

---

src/spaceone/cost_analysis/model/cost_model.py

- fix wrong index in CostQueryHistory

fix: fix wrong index in CostQueryHistory

---

src/spaceone/cost_analysis/service/job_service.py

- change args when calling `analyze_costs` func

refactor: change args when calling analyze_costs func

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py

- exception handling when budget notification fails

refactor: exception handling when budget notification fails

---

src/spaceone/cost_analysis/plugin/data_source/skeleton/conf/global_conf.py

feat: add skeleton code

---

src/spaceone/cost_analysis/plugin/data_source/interface/grpc/__init__.py
src/spaceone/cost_analysis/plugin/data_source/model/cost_request.py
src/spaceone/cost_analysis/plugin/data_source/model/data_source_request.py
src/spaceone/cost_analysis/plugin/data_source/model/data_source_response.py
src/spaceone/cost_analysis/plugin/data_source/model/job_request.py

- fix field name issue in pydantic model

fix: fix field name issue in pydantic model

---

Dockerfile
deploy/helm/Chart.yaml
deploy/helm/templates/deployment-rest.yaml
deploy/helm/templates/deployment-scheduler.yaml
deploy/helm/templates/deployment-worker.yaml

- change run commands
- Dockerfile
- Helm Charts

build: change run commands

---

src/spaceone/cost_analysis/plugin/data_source/skeleton/main.py

- change plugin docs of functions

chore: change plugin docs of functions

---

Dockerfile
pkg/pip_requirements.txt

build: change require pip packages

---

src/spaceone/cost_analysis/plugin/data_source/skeleton/main.py

fix: fix type bug

---

src/spaceone/cost_analysis/plugin/data_source/model/data_source_response.py

- change response model in plugin

refactor: change response model in plugin

---

src/spaceone/cost_analysis/plugin/data_source/model/cost_response.py
src/spaceone/cost_analysis/plugin/data_source/model/data_source_response.py

- change response models in plugin

refactor: change response models in plugin

---

src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/data_source_rule_service.py

- fix type error in data source rule

fix: fix type error

---

src/spaceone/cost_analysis/plugin/data_source/model/cost_response.py

Uncomment data model

---

src/spaceone/cost_analysis/info/data_source_info.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/job_service.py

- add `cost_data_keys` to DataSource model

feat: add cost_data_keys to DataSource model

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/manager/notification_manager.py

feat: add SpaceConnector backend config

---

src/spaceone/cost_analysis/manager/job_manager.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

Add job options 'sync_mode'

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py
src/spaceone/cost_analysis/info/data_source_rule_info.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_manager.py
src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py
src/spaceone/cost_analysis/service/job_task_service.py

- modify datasource_plugin_connector

Modify datasource_plugin_connector

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/budget_usage_service.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/data_source_service.py

- Modify and fix error budget usage apis

Modify and fix error budget usage apis

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/job_service.py

- modify cost info by datasource rule

Modify cost info by datasource rule

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

Modify budget usage api

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/service/budget_service.py

- fix budget create error when 'resource_group = PROJECT'

Fix budget create error when 'resource_group = PROJECT'

---

src/spaceone/cost_analysis/manager/cost_query_set_manager.py
src/spaceone/cost_analysis/model/cost_query_set_model.py
src/spaceone/cost_analysis/service/cost_query_set_service.py

Modify cost_query_set apis

---

src/spaceone/cost_analysis/info/cost_query_set_info.py

-add workspace_id at CostQuerySetInfoZ

Add workspace_id at CostQuerySetInfo

---

src/spaceone/cost_analysis/manager/cost_manager.py

- Fix set and remove cache error

Fix set and remove cache error

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py
src/spaceone/cost_analysis/manager/plugin_manager.py
src/spaceone/cost_analysis/manager/secret_manager.py
src/spaceone/cost_analysis/service/job_service.py

* Apply get token type method by using JWTUtil

fix: apply get token type method by using JWTUtil

---

src/spaceone/cost_analysis/manager/secret_manager.py

fix: fix typo

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/manager/secret_manager.py
src/spaceone/cost_analysis/service/data_source_service.py

Add workspace_id to secret manager when Domain admin register datasource

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py

* add no_token in data source plugin connector

fix: add no_token in data source plugin connector

---

src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/manager/job_task_manager.py

- fix typo when create job task

Fix typo when create job task

---

deploy/helm/Chart.yaml
pkg/pip_requirements.txt
src/setup.py

build: change helm chart

---

src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/plugin_manager.py
src/spaceone/cost_analysis/manager/secret_manager.py

- apply internal authentication

feat: apply internal authentication

---

src/spaceone/cost_analysis/manager/plugin_manager.py

fix: change wrong system token

---

src/spaceone/cost_analysis/error/cost.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/data_source_rule_service.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

feat: add project_group_id filter

---

src/spaceone/cost_analysis/connector/datasource_plugin_connector.py
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/job_task_manager.py

- fix authentication bug in worker

fix: fix authentication bug in worker

---

src/spaceone/cost_analysis/error/cost.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py

- fix `project_group_id` filter bug

fix: fix project_group_id filter bug

---

src/spaceone/cost_analysis/model/cost_model.py

- Add data field at Cost, MonthlyCost Model

Add data field at Cost, MonthlyCost Model

---

src/spaceone/cost_analysis/manager/identity_manager.py

Add debug code

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py

- Modify get system token method at scheduler

Modify get system token method at scheduler

---

src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/service/job_service.py

Add more debug code

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/job_service.py

- Inject domain_id when use system token

Inject domain_id when use system token

---

src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

- add cost_data_keys in monthly aggregate sum field

Add cost_data_keys in monthly aggregate sum field

---

src/spaceone/cost_analysis/service/job_service.py

- edit db cost monthly aggregate query

Edit db cost monthly aggregate query

---

src/spaceone/cost_analysis/service/job_service.py

- modify aggregated_cost_data for data_keys

Modify aggregated_cost_data for data_keys

---

src/spaceone/cost_analysis/interface/grpc/cost_report_config.py
src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_config/request.py
src/spaceone/cost_analysis/model/cost_report_config/response.py
src/spaceone/cost_analysis/plugin/data_source/service/cost_service.py
src/spaceone/cost_analysis/plugin/data_source/service/data_source_service.py
src/spaceone/cost_analysis/plugin/data_source/service/job_service.py
src/spaceone/cost_analysis/service/__init__.py
src/spaceone/cost_analysis/service/cost_report_config_service.py

- [] New feature
Add cost report config

Add cost report config

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/connector/smtp_connector.py
src/spaceone/cost_analysis/error/cost_analysis.py
src/spaceone/cost_analysis/info/cost_info.py
src/spaceone/cost_analysis/interface/grpc/__init__.py
src/spaceone/cost_analysis/interface/grpc/cost_report.py
src/spaceone/cost_analysis/interface/grpc/cost_report_config.py
src/spaceone/cost_analysis/interface/grpc/cost_report_data.py
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/manager/cost_report_data_manager.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/request.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/model/cost_report_data/response.py
src/spaceone/cost_analysis/service/__init__.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/template/cost_report_en.html
src/spaceone/cost_analysis/template/cost_report_jp.html
src/spaceone/cost_analysis/template/cost_report_ko.html

- add cost_report, cost_report_data to app

Add cost_report, cost_report_data to app

---

pkg/pip_requirements.txt

build: add pip package jinja2

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- add create cost_report scheduler task

Add create cost_report scheduler task

---

src/spaceone/cost_analysis/interface/grpc/cost_report.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify aggregate cost_report api

Modify aggregate cost_report api

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/cost_report_data_manager.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/model/cost_report_data/response.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Add cost_report_data apis

---

src/spaceone/cost_analysis/interface/grpc/cost_report_data.py
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/__init__.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

-add cost_report_data analyze api

Add cost_report_data analyze api

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify send cost report email condition

Modify send cost report email condition

---

src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

modify send cost report link temporay use pat

Modify send cost report link temporay use pat

---

src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Fix typo at email report period

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/response.py

The `bank_name` field was added to calculate future exchange rates for each bank.

Add `bank_name` field in CostReport

---

src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Fix check workspace error at identity manager

---

src/setup.py

Add template path at setup.py

---

pkg/pip_requirements.txt
src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/currency_manager.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Exchange rates for KRW, USD, and JPY have been added.
I have developed code that provides information on KRW, USD, and JPY for a specific currency. The code utilizes [FinanceDataReader](https://github.com/FinanceData/FinanceDataReader) an open-source project utilizing [Yahoo! Finance](https://finance.yahoo.com/currencies/).

Add exchange rate

---

pkg/pip_requirements.txt
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify url format for get_url api

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/response.py

Add `currency_date` field at CostReport model

Add `currency_date` field at CostReport model

---

src/spaceone/cost_analysis/model/cost_report_config/request.py
src/spaceone/cost_analysis/service/cost_report_config_service.py

- remove workspace_id parameter at CostReportConfig

Remove workspace_id parameter at CostReportConfig

---

src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py

Add default value 'False' for is_last_day when update CostReportConfig

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify get_url api

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

Fix type error

---

src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_config/request.py
src/spaceone/cost_analysis/model/cost_report_config/response.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/model/cost_report_data/response.py

- add language filter at cost report config

Add language filter at cost report config

---

src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_data/response.py

Fix created_at field type

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Add language field at CostReport

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Remove language at CostReport

---

src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Fix typo parameter order

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/currency_manager.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Add exchange currency function

Add exchange currency function

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/currency_manager.py
src/spaceone/cost_analysis/service/cost_report_data_service.py

Fix tuple typo

---

src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/model/cost_report_config/request.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify filter to get send cost report recipients

---

src/spaceone/cost_analysis/model/cost_report/response.py

Convert created_at type field

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/currency_manager.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Get exchange currency by all currencies

Get exchange currency by all currencies

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/currency_manager.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify calculate cost with currency when create cost_report and data

---

src/spaceone/cost_analysis/conf/global_conf.py

- add default EMAIL_SERVICE_NAME

Add default EMAIL_SERVICE_NAME

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- Modify cost report detail url

Modify cost report detail url

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify report number generator

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify get_report_start_num method

---

src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Modify delete cost_reports_data location

---

src/spaceone/cost_analysis/model/cost_report_data/database.py

* Change max length in CostReportData model

Change max length in CostReportData model

---

.github/workflows/check-pull-request.yml
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/model/job_model.py
src/spaceone/cost_analysis/model/job_task_model.py
src/spaceone/cost_analysis/service/job_service.py

- add 'created_at' field minimal field at Job,JobTask model

Add 'created_at' field minimal field at Job,JobTask model

---

src/spaceone/cost_analysis/interface/grpc/data_source.py
src/spaceone/cost_analysis/manager/secret_manager.py
src/spaceone/cost_analysis/service/data_source_service.py

-  modify logic for manual sync duplicated job
* #198

Modify logic for manual sync duplicated job

---

src/spaceone/cost_analysis/service/job_service.py

- fix plugin data access error
* #199

Fix plugin data access error

---

src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/model/data_source_account/database.py
src/spaceone/cost_analysis/service/job_service.py

- fix connect account policy logic 
* #199

Fix connect account policy logic 

---

src/spaceone/cost_analysis/service/job_service.py

- fix job cancel error because of required 'workspace_id' field

Fix job cancel error because of required 'workspace_id' field

---

src/spaceone/cost_analysis/service/job_service.py

- fix update sync state of ds_account when job closed 
* #199

Fix update sync state of ds_account when job closed 

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py

- add change query filter for v_workspace_id
* #199

Add change query filter for v_workspace_id

---

src/spaceone/cost_analysis/manager/cost_manager.py

- add modify workspace_id filter and group_by response (#199)
* #199

Add modify workspace_id filter and group_by response

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/model/data_source_account/database.py
src/spaceone/cost_analysis/service/job_service.py

- [ㅌ] Improvement
- modify change v_workspace_id fileter location
* #199

Modify change v_workspace_id fileter location

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/cost_service.py

- modify change cost data parameter
* #199

Modify change cost data parameter

---

src/spaceone/cost_analysis/service/data_source_service.py

- add connected_workspace_id parameter list DataSource api
* #199

Add connected_workspace_id parameter list DataSource api

---

src/spaceone/cost_analysis/manager/data_source_rule_manager.py

- fix indent error when change cost data
* #199

Fix indent error when change cost data

---

src/spaceone/cost_analysis/service/job_service.py

- Add data_source_id parameter for cost stat

Add data_source_id parameter for cost stat

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/model/data_source_account/request.py
src/spaceone/cost_analysis/service/data_source_account_service.py

Fix reset api for data source account

---

src/spaceone/cost_analysis/info/data_source_info.py
src/spaceone/cost_analysis/interface/grpc/data_source_account.py
src/spaceone/cost_analysis/manager/data_source_manager.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/data_source_account_service.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

- add data_source_account and connected workspace count field at 'DataSource'
* #199

Add data_source_account and connected workspace count field at 'DataSource'

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- add convert function virtual workspace id and workspace id 
- fix budget cost float point error

Add convert function virtual workspace id and workspace id 

---

src/spaceone/cost_analysis/service/data_source_account_service.py

- add check workspace when update data_source_accountZ
* #199

Add check workspace when update data_source_account

---

src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/data_source_rule_service.py

'DOMAIN_OWNER' -> 'DOMAIN_ADMIN'
- fix data source rule permission

Fix data source rule permission

---

src/spaceone/cost_analysis/interface/grpc/data_source_account.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/model/data_source_account/request.py
src/spaceone/cost_analysis/service/data_source_account_service.py

- add analyze api for DataSourceAccount

Add analyze api for DataSourceAccount

---

src/spaceone/cost_analysis/service/data_source_account_service.py

- modify update data_source_account count field at DataSource

Modify update data_source_account count field at DataSource

---

src/spaceone/cost_analysis/manager/data_source_manager.py
src/spaceone/cost_analysis/service/data_source_account_service.py

- fix connected workspace calculation error

Fix connected workspace calculation error

---

src/spaceone/cost_analysis/manager/data_source_manager.py

- fix filter duplicate connected workspaces for DataSource related with DataSourceAccount
* #199

Fix filter duplicate connected workspaces for DataSource related with DataSourceAccount

---

src/spaceone/cost_analysis/plugin/data_source/conf/global_conf.py
src/spaceone/cost_analysis/plugin/data_source/interface/grpc/__init__.py
src/spaceone/cost_analysis/plugin/data_source/interface/grpc/cost.py
src/spaceone/cost_analysis/plugin/data_source/model/cost_request.py

- fix cost plugin get_linked account response error

Fix cost plugin get_linked account response error

---

src/spaceone/cost_analysis/plugin/data_source/interface/grpc/cost.py

- fix cost plugin get_linked account return type

Fix cost plugin get_linked account return type

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py

- fix convert v_workspace_id logic at analyze response

Fix convert v_workspace_id logic at analyze response

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_account_manager.py
src/spaceone/cost_analysis/model/data_source_account/database.py
src/spaceone/cost_analysis/model/data_source_account/response.py
src/spaceone/cost_analysis/service/data_source_account_service.py

- add `is_linked` field at DataSourceAccount

Add `is_linked` field at DataSourceAccount

---

src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py

- modify workspace,project max length '40' -> '255'

Modify workspace,project max length '40' -> '255'

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- set cost report data list limit

Set cost report data list limit

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/service/cost_report_data_service.py

- modify cost report data index

Modify cost report data index

---

src/spaceone/cost_analysis/plugin/data_source/model/job_response.py

- add 'filter' field at Changed class

Add 'filter' field at Changed class

---

src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- add feature create default cost report config by scheduler job

Add feature create default cost report config by scheduler job

---

src/spaceone/cost_analysis/interface/grpc/cost.py
src/spaceone/cost_analysis/interface/grpc/data_source.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/data_source_manager.py
src/spaceone/cost_analysis/model/cost/response.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/request.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/model/cost_report_data/response.py
src/spaceone/cost_analysis/model/data_source/request.py
src/spaceone/cost_analysis/model/data_source/response.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/data_source_service.py

- [ x New feature
- add new feature 'update_permissions' for DataSource
- modify cost_report_data and cost_report_config index

Add new feature 'update_permissions' for DataSource

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/cost_report_config_service.py

Modify check group by logic 

---

src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/service/cost_report_data_service.py

- add Workspace Member permissions for cost report data analyze

Add Workspace Member permissions for cost report data analyze

---

src/spaceone/cost_analysis/info/data_source_info.py

feat: add permissions field at datasource info

---

src/spaceone/cost_analysis/service/job_service.py

- fix delete cost parameter order

Fix delete cost parameter order

---

src/spaceone/cost_analysis/service/cost_service.py

- add v-workspace-id filter at cost stat service

Add v-workspace-id filter at cost stat service

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/cost_service.py

- modify convert virtual workspace id to workspace id when get, delete list

Modify convert virtual workspace id to workspace id when get, delete list

---

src/spaceone/cost_analysis/service/cost_service.py

- modify get data_source_id logic when cost.stat

Modify get data_source_id logic when cost.stat

---

src/spaceone/cost_analysis/interface/grpc/data_source.py
src/spaceone/cost_analysis/manager/data_source_manager.py
src/spaceone/cost_analysis/model/data_source/request.py
src/spaceone/cost_analysis/model/data_source/response.py
src/spaceone/cost_analysis/service/data_source_service.py

- add cost_data_keys filter at data_source 'get' and 'list' api

Add cost_data_keys filter at data_source 'get' and 'list' api

---

src/spaceone/cost_analysis/service/data_source_service.py

- add default only field value as empty list

Add default only field value as empty list

---

src/spaceone/cost_analysis/interface/grpc/data_source.py

- modify grpc interface DataSource.register

Modify grpc interface DataSource.register

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- add issue_date at IN_PROGRESS cost_report_data

Add issue_date at IN_PROGRESS cost_report_data

---

src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py

Add scheduler log

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify cost report and cost report delete logic

Modify cost report and cost report delete logic

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- remove cost report at for loop

Remove cost report at for loop

---

src/spaceone/cost_analysis/manager/cost_manager.py

- Add check dict type group_by when analyze

Add check dict type group_by when analyze

---

src/spaceone/cost_analysis/plugin/data_source/skeleton/main.py
src/spaceone/cost_analysis/service/data_source_service.py

- modify update_permission for removing duplicated elements

Modify update_permission for removing duplicated elements

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify cost report create retry logic

Modify cost report create retry logic

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- fix and add cost report create retry condition

Fix and add cost report create retry condition

---

src/spaceone/cost_analysis/service/job_service.py

- optimize memory when synchronizing costs

refactor: optimize memory when synchronizing costs

---

src/spaceone/cost_analysis/service/job_service.py

- fix cursor bug
- remove debug code

fix: fix cursor bug

---

src/spaceone/cost_analysis/service/job_service.py

- improve performance when aggregating monthly costs

refactor: improve performance when aggregating monthly costs

---

src/spaceone/cost_analysis/plugin/data_source/model/data_source_response.py
src/spaceone/cost_analysis/plugin/data_source/model/job_response.py

- add 'additional_info' field at PluginMetadata model

Add 'additional_info' field at PluginMetadata model

---

src/spaceone/cost_analysis/service/job_service.py

- temporary remove tags group by aggregation after cost sync

Temporary remove tags group by aggregation after cost sync

---

src/spaceone/cost_analysis/info/data_source_rule_info.py
src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/data_source_rule_service.py

- add 'match_workspace' at DataSourceRuleActions

Add 'match_workspace' at DataSourceRuleActions

---

src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- fix report month error when run CostReportConfig

Fix report month error when run CostReportConfig

---

src/spaceone/cost_analysis/service/data_source_rule_service.py

- remove duplicate actions check logic

Remove duplicate actions check logic

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/service/data_source_service.py

Fix get currency info 

---

src/spaceone/cost_analysis/service/job_service.py

- remove unused import package at job_service.py

Remove unused import package at job_service.py

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/job_service.py

- fix convert workspace_id error at group_by because for v_workspace_id

fix: fix convert workspace_id error at group_by because for v_workspace_id

---

src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/config_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/model/__init__.py
src/spaceone/cost_analysis/model/unified_cost/database.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- Refactor unified cost run logic

Refactor unified cost run logic

---

src/spaceone/cost_analysis/manager/unified_cost_job_manager.py
src/spaceone/cost_analysis/service/job_service.py

- update logic for creating aggregate monthly cost after each job task completion

Update logic for creating aggregate monthly cost after each job task completion

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/service/job_service.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- modify unified cost run schedule condition

Modify unified cost run schedule condition

---

src/spaceone/cost_analysis/service/job_service.py

- recover cost aggregate monthly cost

Recover cost aggregate monthly cost

---

src/spaceone/cost_analysis/service/unified_cost_service.py

- modify run last month unified cost parameter by scheduler

Modify run last month unified cost parameter by scheduler

---

src/spaceone/cost_analysis/service/job_service.py

Refactor Job Process

---

src/spaceone/cost_analysis/model/unified_cost/database.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- add logic for creating workspace_id `None` value unified cost

Add logic for creating workspace_id `None` value unified cost

---

src/spaceone/cost_analysis/model/data_source_account/request.py
src/spaceone/cost_analysis/service/data_source_account_service.py

- modify reset data source account option

Modify reset data source account option

---

src/spaceone/cost_analysis/service/job_service.py

- optimize query for performance

refactor: optimize query for performance

---

src/spaceone/cost_analysis/service/unified_cost_service.py

…ce-id
- fix create unified cost when workspace is None and has v-workspace-id

Fix create unified cost when workspace is None and has v-workspace-id

---

src/spaceone/cost_analysis/service/job_service.py

- fix bug when syncing cost job

fix: fix bug when syncing cost job

---

src/spaceone/cost_analysis/service/job_service.py

- fix bug query when syncing costs

fix: fix bug query when syncing costs

---

src/spaceone/cost_analysis/manager/config_manager.py
src/spaceone/cost_analysis/service/cost_query_set_service.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- Fix typo at exchange data source value

Fix typo at exchange data source value

---

src/spaceone/cost_analysis/manager/cost_manager.py

- add debugging code to stat query

chore: add debugging code 

---

src/spaceone/cost_analysis/service/cost_service.py

- remove pagination from analyze and stat queries

refactor: remove pagination from analyze and stat queries

---

src/spaceone/cost_analysis/service/unified_cost_service.py

- Fix delete unified cost error

Fix delete unified cost error

---

src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/service/job_service.py

modify job "update_at" update & duplicated check logic
Do not check job duplication when it is MANUAL

feat: modify job "update_at" update & duplicated check logic

---

src/spaceone/cost_analysis/manager/data_source_rule_manager.py
src/spaceone/cost_analysis/service/job_service.py

refactor: refactor cost sync job

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/model/cost_model.py

* Change search index in Cost Model

Change search index in Cost Model

---

src/spaceone/cost_analysis/error/cost.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/service/cost_service.py
src/spaceone/cost_analysis/service/job_service.py

Change index in Cost Model

---

src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/model/cost_model.py
src/spaceone/cost_analysis/model/job_task_model.py
src/spaceone/cost_analysis/plugin/data_source/model/job_response.py
src/spaceone/cost_analysis/service/job_service.py

- add task_changed field at job task and modify cost index
- delete cost with jobtask logic

Add task_changed field at job task and modify cost index

---

src/spaceone/cost_analysis/interface/task/v1/unified_cost_run_scheduler.py
src/spaceone/cost_analysis/service/job_service.py

- fix type error when get changed value at job task

Fix type error when get changed value at job task

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/job_service.py

* Add include_count option when executing _delete_changed_cost_data method
* Change log when closing job
* Improve index overwrite phenomenon

Add include_count options when executing delete method in Job

---

src/spaceone/cost_analysis/service/job_service.py

Correct logic for manual duplicate job time check

---

src/spaceone/cost_analysis/manager/data_source_account_manager.py

- fix workspace scope change cost data rule param

Fix workspace scope change cost data rule param

---

src/spaceone/cost_analysis/info/data_source_info.py
src/spaceone/cost_analysis/interface/grpc/data_source.py
src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
src/spaceone/cost_analysis/model/data_source/request.py
src/spaceone/cost_analysis/model/data_source/response.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/data_source_service.py
src/spaceone/cost_analysis/service/job_service.py

* add schedule field to DataSource

add: add schedule field to DataSource

---

src/spaceone/cost_analysis/manager/unified_cost_manager.py

Recover unified cost cache

---

src/spaceone/cost_analysis/service/unified_cost_service.py

- modify delete unified cost logic about not exist workspace

Modify delete unified cost logic about not exist workspace

---

src/spaceone/cost_analysis/manager/cost_manager.py

- modify analyze Daily date range 1 month -> 31days

Modify analyze Daily date range 1 month -> 31days

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/info/budget_info.py
src/spaceone/cost_analysis/info/budget_usage_info.py
src/spaceone/cost_analysis/interface/grpc/budget.py
src/spaceone/cost_analysis/interface/grpc/budget_usage.py
src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/model/__init__.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/model/budget_usage/database.py
src/spaceone/cost_analysis/model/budget_usage/request.py
src/spaceone/cost_analysis/model/budget_usage/response.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/budget_usage_service.py

- modify budget and budget usages all apis

Modify budget and budget usages all apis

---

src/spaceone/cost_analysis/service/budget_usage_service.py

- add convert model decorator at budget usage analyze api

Add convert model decorator at budget usage analyze api

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/job_service.py
src/spaceone/cost_analysis/service/unified_cost_service.py
src/spaceone/cost_analysis/template/budget_usage_alert_en.html
src/spaceone/cost_analysis/template/budget_usage_alert_ko.html

- add budget alert notification function

Add budget alert notification function

---

src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py

- add logic for project based budget

Add logic for project based budget

---

Dockerfile
src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/model/budget_usage/request.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/budget_usage_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify field name notifications -> notification

Modify field name notifications -> notification 

---

src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/service/budget_service.py

- add budget_manager_id field for Budget

Add budget_manager_id field for Budget

---

src/spaceone/cost_analysis/service/budget_service.py

- add convert model decorator at stat api

Add convert model decorator at stat api

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/model/budget_usage/database.py
src/spaceone/cost_analysis/service/budget_service.py

- add budget year field and modify budget update scheduler

Add budget year field and modify budget update scheduler

---

src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget_usage/request.py
src/spaceone/cost_analysis/model/unified_cost/database.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/service/budget_usage_service.py

- modify budget and budget usage index order
-

Modify budget and budget usage index order

---

src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
src/spaceone/cost_analysis/interface/task/v1/cost_report_run_scheduler.py

- modify cost report run scheduler class name

Modify cost report run scheduler class name

---

.github/workflows/dispatch_daily_build.yaml

- update workflow to use Ubuntu 22.04

Update workflow to use Ubuntu 22.04

---

src/spaceone/cost_analysis/service/budget_service.py

- Add `budget_manageR_id` element for budget stat keyword filter query

Add `budget_manageR_id` element for budget stat keyword filter query

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/budget_service.py

- add error handling for unverified budget managers and update notification checks

Add error handling for unverified budget managers and update notification checks

---

src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/service/budget_service.py

- enhance budget management with optional workspace_id and refactor budget usage notification logic

Enhance budget management with optional workspace_id and refactor budget usage notification logic

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/model/budget/request.py
src/spaceone/cost_analysis/model/budget/response.py
src/spaceone/cost_analysis/service/budget_service.py

Add budget state field and improve budget usage update logic

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/service/budget_service.py

- implement budget state update job scheduling and enhance budget state management

Implement budget state update job scheduling and enhance budget state management

---

src/spaceone/cost_analysis/model/budget_usage/request.py
src/spaceone/cost_analysis/service/budget_usage_service.py

… filter
- Add service_account_id field to budget usage list request query filter

Add service_account_id field to budget usage list request query filter

---

src/spaceone/cost_analysis/interface/grpc/cost_report.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/plugin/data_source/model/cost_request.py
src/spaceone/cost_analysis/service/__init__.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/cost_report_data_service.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Reverts cloudforet-io/cost-analysis#340

Revert "Migrate cost report services to UnifiedCost model"

---

src/spaceone/cost_analysis/manager/unified_cost_manager.py

- add Unified cost analysis with domain_id filtering and project_group_id

Add Unified cost analysis with domain_id filtering and project_group_id

---

src/spaceone/cost_analysis/error/budget.py
src/spaceone/cost_analysis/service/budget_service.py

- add error handling for duplicated budget thresholds

Add error handling for duplicated budget thresholds

---

src/spaceone/cost_analysis/model/cost_report_config/response.py

Correct adjustment_options type annotation

---

src/spaceone/cost_analysis/error/cost_report_config.py
src/spaceone/cost_analysis/error/report_adjustment_policy.py
src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
src/spaceone/cost_analysis/service/cost_report_config_service.py
src/spaceone/cost_analysis/service/report_adjustment_policy_service.py

Add validation for project and workspace IDs in adjustment policy

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/report_adjustment_policy_service.py

Enhance cost report generation with project name mapping and metadata handling

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/manager/report_adjustment_manager.py
src/spaceone/cost_analysis/manager/report_adjustment_policy_manager.py
src/spaceone/cost_analysis/model/report_adjustment/database.py
src/spaceone/cost_analysis/model/report_adjustment/request.py
src/spaceone/cost_analysis/model/report_adjustment/response.py
src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
src/spaceone/cost_analysis/service/report_adjustment_service.py

Refactor adjustment policy to use policy_filter for workspace and project IDs

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py

Update currency_end_date to use the instance's currency_date

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/cost_query_set_manager.py
src/spaceone/cost_analysis/manager/job_manager.py
src/spaceone/cost_analysis/manager/job_task_manager.py
src/spaceone/cost_analysis/manager/unified_cost_job_manager.py

fix: fix declare model logic

---

src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
src/spaceone/cost_analysis/service/report_adjustment_service.py

- refactor report adjustment policy to use query parameters and update scope handling

Refactor report adjustment policy to use query parameters and update scope handling

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/request.py

Update status choices in CostReport model to include 'ADJUSTING  and 'DONE'

---

src/spaceone/cost_analysis/model/cost_report/request.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Rename 'workspace_name' to 'name' in cost report service and related files

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

fix CostReport & UnifiedCost Logic

fix: fix CostReport & UnifiedCost Logic

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/model/cost_report_data/request.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

Rename 'workspace_name' to 'name' in service, database, and request/response models

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/connector/currency_connector.py
src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
src/spaceone/cost_analysis/manager/cost_report_config_manager.py
src/spaceone/cost_analysis/manager/cost_report_data_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/model/cost_report/response.py
src/spaceone/cost_analysis/model/cost_report_config/database.py
src/spaceone/cost_analysis/model/cost_report_config/request.py
src/spaceone/cost_analysis/model/cost_report_config/response.py
src/spaceone/cost_analysis/model/cost_report_data/database.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/template/cost_report_en.html
src/spaceone/cost_analysis/template/cost_report_ja.html
src/spaceone/cost_analysis/template/cost_report_ko.html

Refactor cost report handling to use 'name' instead of 'workspace_name' and improve currency management

---

pkg/pip_requirements.txt
src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/connector/databricks_connector.py
src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
src/spaceone/cost_analysis/model/data_source/request.py
src/spaceone/cost_analysis/model/data_source_model.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/data_source_service.py

- add support for WAREHOUSE data source type and integrate Databricks

Add support for WAREHOUSE data source type and integrate Databricks

---

src/spaceone/cost_analysis/connector/databricks_connector.py

Update DatabricksConnector to use 'billed_month' for date formatting and change GROUP BY clause to 'ALL'

---

src/spaceone/cost_analysis/error/report_adjustment_policy.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/report_adjustment_policy_service.py

* fix CostReport list query issue

fix: fix CostReport list query issue

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix create report month & calculate date logic

fix: fix create report month & calculate date logic

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix delete DONE Report issue & create useless in_progress logic

fix: fix delete DONE Report issue & create useless in_progress logic

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix some logic & add fields to cost_report_data just source code

fix: fix some logic & add fields to cost_report_data just source code

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix calculate report date logic

fix: fix calculate report date logic

---

src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

fix: fix cost report key error

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix cost report date calculate logic

fix: fix cost report date calculate logic

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix CostReport delete query filter error

fix: fix CostReport delete query filter error

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix CostReport update to expired method parameter error

fix: fix CostReport update to expired method parameter error

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix scheduled cost report logic

fix: fix scheduled cost report logic
