cloudforet-io/cost-analysis

src/spaceone/cost_analysis/info/cost_info.py
src/spaceone/cost_analysis/manager/cost_manager.py

Exchange rate handling in Cost analysis is deprecated.
The cost value provided by the individual CSP is used as it is, and the USD cost value provided by the plugin is used as it is.

feat: exchange rate is deprecated

---

src/spaceone/cost_analysis/service/data_source_account_service.py

- fix data_source_account update error

Fix Data_source_account update error

---

src/spaceone/cost_analysis/plugin/data_source/model/data_source_response.py

- add 'account_match_key' field for init cost plugin metadata

Add 'account_match_key' field for init cost plugin metadata

---

src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/job_service.py

- add 'data_source_id' and 'v_workspace' field when execute request get_tasks to plugin

Add 'data_source_id' and 'v_workspace' field when execute request get_tasks to plugin

---

src/spaceone/cost_analysis/service/cost_report_config_service.py

- fix append query filter for cost report config 'domain' -> 'domain_id'

Fix append query filter for cost report config 'domain' -> 'domain_id'

---

src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/job_service.py

- add defensive code when creating cost report data by scheduler

Add defensive code when creating cost report data by scheduler

---

src/spaceone/cost_analysis/manager/cost_report_manager.py
src/spaceone/cost_analysis/model/__init__.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

- Remove email manager at CostReportService init

Remove email manager at CostReportService init

---

src/spaceone/cost_analysis/service/cost_report_serivce.py

- modify delete step for cost_report_data

Modify delete step for cost_report_data

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/job_service.py

Add Debug Code

---

src/spaceone/cost_analysis/conf/global_conf.py
src/spaceone/cost_analysis/service/cost_report_serivce.py
src/spaceone/cost_analysis/service/data_source_rule_service.py

- fix report month error when run CostReportConfig

Fix report month error when run CostReportConfig

---

src/spaceone/cost_analysis/service/job_service.py

chore: add debugging logs

---

src/spaceone/cost_analysis/service/unified_cost_service.py

- modify delete old unified cost logic

Modify delete old unified cost logic

---

src/spaceone/cost_analysis/manager/unified_cost_job_manager.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- Modify get `is_confirmed` value for aggregation month

Modify get `is_confirmed` value for aggregation month

---

src/spaceone/cost_analysis/manager/identity_manager.py
src/spaceone/cost_analysis/service/unified_cost_service.py

- fix wrong aggregation month value input

XFix wrong aggregation month value input

---

src/spaceone/cost_analysis/service/job_service.py

refactor: apply hint for performance

---

src/spaceone/cost_analysis/service/job_service.py

refactor: optimize job progress

---

src/spaceone/cost_analysis/manager/cost_manager.py
src/spaceone/cost_analysis/service/job_service.py

- optimize query for performance

refactor: optimize query for performance

---

src/spaceone/cost_analysis/manager/unified_cost_manager.py
src/spaceone/cost_analysis/service/unified_cost_service.py

Fix yearly unified cost bug

---

src/spaceone/cost_analysis/manager/unified_cost_manager.py

- fix yearly unified cost missing cache key error

Fix yearly unified cost missing cache key error

---

src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
src/spaceone/cost_analysis/manager/budget_manager.py
src/spaceone/cost_analysis/manager/budget_usage_manager.py
src/spaceone/cost_analysis/manager/email_manager.py
src/spaceone/cost_analysis/model/budget/database.py
src/spaceone/cost_analysis/service/budget_service.py
src/spaceone/cost_analysis/template/budget_usage_alert_en.html
src/spaceone/cost_analysis/template/budget_usage_alert_ko.html

- enhance budget notification logic

Enhance budget notification logic

---

src/spaceone/cost_analysis/model/budget_usage/database.py

- Add service_account_id field to budget usage model

Add service_account_id field to budget usage model

---

src/spaceone/cost_analysis/model/budget/request.py

- update workspace_id field to be optional when get budget info

Update workspace_id field to be optional when get budget info

---

src/spaceone/cost_analysis/model/report_adjustment/database.py

- update 'unit' choices in ReportAdjustment model to include 'PERCENT' instead of 'PERCENTAGE'

Update 'unit' choices in ReportAdjustment model to include 'PERCENT' instead of 'PERCENTAGE'

---

src/spaceone/cost_analysis/model/cost_report/database.py
src/spaceone/cost_analysis/model/cost_report/request.py
src/spaceone/cost_analysis/service/cost_report_serivce.py

* fix CostReport Date LogIc & add status EXPIRED and some logic

fix: fix CostReport Date LogIc & add status EXPIRED and some logic
